# configuracion propia de vagrant
vagrant_conf:
    # si da el error "mkdir: cannot create directory ‘/tmp/vagrant-cache/apt’: Permission denied"
    # prueba a deshabilitar cachier, levantar la maquina, destruirla y habilitarlo de nuevo
    cachier: true
    rsync__auto: True
    rsync__exclude: 
      - models
    # no funciona rsync_auto con symlinks, por lo que hacemos que se puedan configurar las rutas sincronizadas
    synced_folders:
      provisioning: ./provisioning

ansible_master:
  hostname: ansible-master
  cpus: 1
  ip: 10.0.1.10
  box: ubuntu/xenial64
  box_url: ubuntu/xenial64
  ram: 1024

nodes:
  - loadbalancer:
    hostname: loadbalancer
    cpus: 1
    ip: 10.0.1.11
    box: ubuntu/xenial64
    box_url: ubuntu/xenial64
    ram: 1024
    disksize: 20GB
    extra_disks: []

  # - machine3:
  #   hostname: machine3
  #   cpus: 1
  #   ip: 10.0.0.12
  #   box: centos/7
  #   box_url: centos/7
  #   ram: 1024
  #   extra_disks:
  #     - 5120
  #     - 5120
