---
# tasks file for nginx
- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: delete default index page
  file: path=/var/www/html/index.nginx-debian.html state=absent

- name: copy custom web
  copy: src=index.html dest=/var/www/html mode=644
  notify: restart nginx
