---
# tasks file for apache2

- name: install apache2
  apt: name=apache2 state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install httpd
  yum: name=httpd state=present update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: copy custom web
  template: src=index.html.j2 dest=/var/www/html/index.html mode=644
  notify: restart apache2

- debug: var=hostvars['apache2']['ansible_facts']['os_family']
- debug: var=hostvars['docker']['ansible_enp0s8']['ipv4']['address']