---
master:
  hosts:
    ansible-master:
      ansible_connection: local

linux:
  children:
    apache2:
      hosts:
        apache2:
    docker:
      hosts:
        docker:
    nginx:
      hosts:
        nginx:
  vars:
    ansible_become: true
  
