---
master:
  hosts:
    ansible-master:
      ansible_connection: local
linux:
  children:
    nginx:
      hosts:
        nginx:
    apache2:
      hosts:
        apache2:
  vars:
    ansible_become: true
  
