# https://www.digitalocean.com/community/tutorials/how-to-automate-installing-wordpress-on-ubuntu-14-04-using-ansible
---
- hosts: all
  become: true
  tasks:
    - name: install tools
      apt: 
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars:
        packages:
          - htop
          - tree       